# name: Generate Snake

# on:
#   schedule: # execute every 8 hours
#     - cron: "0 2 * * 1-5"
#   workflow_dispatch:

# jobs:
#   build:
#     name: Jobs to update datas
#     runs-on: ubuntu-latest
#     steps:
#       # Snake Animation
#       - uses: Platane/snk@master
#         id: snake-gif
#         with:
#           github_user_name: JustinJDaniel
#           # next lines generate the files on a branch called "master". This keeps the main branch from cluttering up.
#           svg_out_path: dist/github-contribution-grid-snake.svg
#           # gif_out_path: dist/github-contribution-grid-snake.gif

#       # show the status of the build. Makes it easier for debugging (if there's any issues).
#       - run: git status

#       # Push the changes
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: master
#           force: true
          
#       - uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           # Don't Run this workflow on your default branch
#           target_branch: master
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
